---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: vllm-aug16
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vllm-aug16 
  name: vllm-aug16
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi