apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: vllm-aug16
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vllm-aug16 
  name: vllm-aug16
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: vllm-aug16 
    weight: 100 
  wildcardPolicy: None
