apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vllm-aug16 
  janus-idp.io/tekton: vllm-aug16
  backstage.io/kubernetes-id: vllm-aug16
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vllm-aug16
resources: 
- application-dev.yaml